///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// CLI SUBMODULE CONSTANTS ===========================================================================================

module.exports = {
    flags: {
        fee: {
            hint: "Qualify how much fee to pay: stinky|low|medium|high|opulent (default: medium)",
            param: ":fee_tag",
        },
        path: {
            hint: "Derive spending address from BIP-32 path",
            param: "m/:path"
        },
    },
    router: {
        address: {
            hint: "Show wallet's public key hash"
        },
        balance: {
            hint: "Show wallet's available balance.",
        },
        stake: {
            hint: "Stake specified amount of Wits by using given authorization code.",
            params: "NANOWITS",
            options: { 
                authorization: { 
                    hint: "Stake authorization code as generated by a validator", 
                    param: ":hexstring"
                },
                withdrawer: {
                    hint: "(Optional) Address allowed to withdraw the stake",
                    param: ":pkh"
                },
            }
        },
        unstake: {
            hint: "Unstake specified amount of Wits from given validator",
            params: "NANOWITS",
            options: {
                validator: {
                    hint: "Validator address from where to withdraw the stake",
                    param: ":pkh"
                },
            }
        },
        transfer: {
            hint: "Transfer specified amount of Wits to given address.",
            params: "NANOWITS",
            options: {
                to: {
                    hint: "Destination address",
                    param: ":pkh",
                },
            },
        },
        utxos: {
            hint: "List wallet's available UTXOs.",
        },
        splitUtxos: {
            hint: "Lorem ipsum.",
        },
        joinUtxos: {
            hint: "Lorem ipsum.",
        },
    },
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// CLI SUBMODULE COMMANDS ============================================================================================


